version: '3.9'

services:
  frontend:
    image: stratiscr.azurecr.io/bsfe:v4
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    env_file:
      -  ../envs/common-frontend.env
